--1
--CREATE DATABASE BRADESCO_BOOTCAMP

--2
--CREATE TABLE usuarios (
--id INT,
--nome VARCHAR(255) NOT NULL, -- NOME DO USUARIO,
--email VARCHAR(100) NOT NULL UNIQUE, -- EMAIL DO USUARIO
--endereco VARCHAR(50) NOT NULL, -- ENDERECO
--data_nascimento DATE NOT NULL
--);

--3
--CREATE TABLE destinos(
--id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--nome VARCHAR(255) NOT NULL, -- NOME DO DESTINO
--descricao VARCHAR(255) NOT NULL -- DESCRIÇÃO DO DESTINO
--);

--4
--CREATE TABLE reservas(
--id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--id_usuario INT, -- REFERÊNCIA AO ID DO USUÁRIO QUE FAZ A RESERVA
--id_destino INT, -- REFERÊNCIA AO ID DO DESTINO DA RESERVA
--data DATE, -- DATA DA RESERVA
--status VARCHAR(255) NOT NULL, -- STATUS DA RESERVA (CONFIRMADA, PENDENTE, CANCELADA, ETC...)
--);