--1
--CREATE DATABASE BRADESCO_BOOTCAMP

--2
--CREATE TABLE usuarios (
--id INT,
--nome VARCHAR(255) NOT NULL, -- NOME DO USUARIO,
--email VARCHAR(100) NOT NULL UNIQUE, -- EMAIL DO USUARIO
--endereco VARCHAR(50) NOT NULL, -- ENDERECO
--data_nascimento DATE NOT NULL
--);

-- 3
--CREATE TABLE destinos(
--id INT,
--nome VARCHAR(255) NOT NULL, -- NOME DO DESTINO
--descricao VARCHAR(255) NOT NULL -- DESCRIÇÃO DO DESTINO
--);
